server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOriginPatterns: "*"   # 🔥 React access allowed
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: false      # 🔥 IMPORTANT FIX

      routes:

        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/teams/**

        - id: player-service
          uri: lb://player-service
          predicates:
            - Path=/players/**

        - id: match-service
          uri: lb://match-service
          predicates:
            - Path=/matches/**

        - id: scoring-service
          uri: lb://scoring-service
          predicates:
            - Path=/scoring/**

        - id: stats-service
          uri: lb://stats-service
          predicates:
            - Path=/api/stats/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

management:
  endpoints:
    web:
      exposure:
        include: "gateway,health,info,metrics,env,beans"
  endpoint:
    gateway:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    hostname: localhost
