# ---------- Stage 1: Build ----------
FROM maven:3.9.1-eclipse-temurin-17 AS build
WORKDIR /workspace

COPY . .

RUN mvn -B -f pom.xml -pl backend/discovery-service -am clean package -DskipTests


# ---------- Stage 2: Run ----------
FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app

COPY --from=build /workspace/backend/discovery-service/target/*SNAPSHOT.jar /app/app.jar

EXPOSE 8761

ENTRYPOINT ["java","-jar","/app/app.jar"]
